version: "3.8"
services:
  proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
    volumes:
      - ./credentials.json:/secrets/cloudsql/credentials.json
    ports:
      - "54320:54320"
    command: >
      /cloud_sql_proxy 
      -instances=${CLOUD_SQL_INSTANCE_NAME}=tcp:0.0.0.0:54320
      -credential_file=/secrets/cloudsql/credentials.json
